services:
  - type: web
    name: avukat-ajanda-api-py
    runtime: docker
    dockerfilePath: ./Dockerfile
    repo: https://github.com/serhattopaloglu25/avukat-ajanda-backend-py
    branch: main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: avukatajanda-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: https://avukatajanda.com,http://localhost:3000
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
    
databases:
  - name: avukatajanda-db
    databaseName: avukatajanda
    user: avukatajanda
    plan: starter
